
# General Configuration
export ALLOW_MISSING_DEPENDENCIES=true
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
export LC_ALL="C"
export OF_MAINTAINER="1ndevelopment"
export FOX_BUILD_TYPE="1ndev"
export FOX_VERSION="R12.1"
export FOX_TARGET_DEVICES="CG65"
export FOX_BUILD_DEVICE="CG65"
export TARGET_ARCH="arm64-v8a"
export OF_CLASSIC_LEDS_FUNCTION=0
export FOX_DELETE_AROMAFM=0
export OF_CLOCK_POS=1
export OF_IGNORE_LOGICAL_MOUNT_ERRORS=1
export OF_FORCE_PREBUILT_KERNEL=1
export OF_NO_SPLASH_CHANGE=0
export OF_STATUS_INDENT_RIGHT=48
export OF_STATUS_INDENT_LEFT=48
export OF_WIPE_METADATA_AFTER_DATAFORMAT=1
export OF_OPTIONS_LIST_NUM=8

# Partition Configurations
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=0
export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system_a"
export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor_a"
export FOX_RECOVERY_INSTALL_PARTITION="/dev/block/by-name/recovery"

# Security Configurations
export OF_ADVANCED_SECURITY=1
export OF_KEEP_DM_VERITY=0
export OF_DISABLE_FORCED_ENCRYPTION=1
export OF_FORCE_DISABLE_FORCED_ENCRYPTION=1
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
export OF_USE_SYSTEM_FINGERPRINT=1

# Build environment stuffs
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export TARGET_DEVICE_ALT="Vortex, CG65"
export BUILD_USERNAME="nobody"
export BUILD_HOSTNAME="android-build"

# Use magisk boot for patching
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1

# Screen specifications
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_CLOCK_POS=0
export OF_SCREEN_H=1600
export OF_STATUS_H=120

# Device stuff
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_FBE_METADATA_MOUNT_IGNORE=1
export OF_PATCH_AVB20=1
export OF_USE_LEGACY_BATTERY_SERVICES=1
export FOX_DRASTIC_SIZE_REDUCTION=1

# Run a process after formatting data to work-around MTP issues
export OF_RUN_POST_FORMAT_PROCESS=1

# OTA for custom ROMs
export OF_SUPPORT_ALL_PAYLOAD_OTA_UPDATES=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=0
export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1

# For some reason this is dumb and necessary
export FOX_BUGGED_AOSP_ARB_WORKAROUND="1601559499"

# Quick Backup list
export OF_QUICK_BACKUP_LIST="/boot;/data;/super;"

# Set default Keymaster Version
export OF_DEFAULT_KEYMASTER_VERSION=4.1

# Add some extras
export FOX_USE_ZIP_BINARY=1
export FOX_USE_TAR_BINARY=1
export FOX_ASH_IS_BASH=1
export FOX_REPLACE_BUSYBOX_PS=1
export FOX_USE_BASH_SHELL=1
#export OF_USE_LZMA_COMPRESSION=1
export FOX_USE_NANO_EDITOR=1
export OF_DONT_KEEP_LOG_HISTORY=1
export OF_NO_SPLASH_CHANGE=1
export FOX_INSTALLER_DISABLE_AUTOREBOOT=1

# Applications Configurations
export FOX_ENABLE_APP_MANAGER=1
